version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:15.8.0-ce.0
    container_name: gitlab
    restart: always
    privileged: true
    hostname: ${GITLAB_HOSTNAME}
    ports:
      - '8090:80'
      - '443:443'
      - '22:22'
    volumes:
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'
      - './config:/etc/gitlab'
    shm_size: '256m'